In [5]:
print('Hello')

Hello


### NumPy arrays - Part I

In [7]:
import numpy as np

In [8]:
mylist = [1,2,3]

In [9]:
type(mylist)

list

In [10]:
np.array(mylist)

array([1, 2, 3])

In [11]:
type(mylist)

list

In [12]:
arr = np.array(mylist)

In [13]:
arr

array([1, 2, 3])

In [14]:
mylist = [[1,2,3],[4,5,6],[7,8,9]]

In [15]:
mylist

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [16]:
mymatrix = np.array(mylist)

In [17]:
mymatrix.shape

(3, 3)

In [18]:
np.arange(0,10) # Generate sequence of number between with stepsize 1 between 0 and 10 (inclusing 0 and excluding 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [20]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [21]:
type(0.)

float

In [22]:
np.zeros((4,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [23]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [24]:
np.ones((5,5)) + 4

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])

In [25]:
np.ones(4) * 100

array([100., 100., 100., 100.])

In [26]:
np.ones(4)/100

array([0.01, 0.01, 0.01, 0.01])

In [27]:
np.linspace(0,10,20) # Evenly space 20 numbers between 0 and 10 inlcuding 0 and 10

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [28]:
np.eye(5) # Create an identity matrix with size 

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### NumPy arrays - Part II

In [30]:
np.random.rand(1) # Create a uniform random number (a sample from uniform distribution between 0 and 1)

array([0.45812654])

In [31]:
np.random.rand(4) # Create 4 uniform random numbers

array([0.98992929, 0.21269405, 0.2617221 , 0.59997929])

In [32]:
np.random.rand(5,5) # Create a 5 by 5 matrix (5 by 5 array) with uniform random numbers

array([[0.84978253, 0.44295248, 0.48222263, 0.43954704, 0.32967835],
       [0.86189348, 0.83131606, 0.13841494, 0.30980995, 0.0187712 ],
       [0.51225783, 0.20691944, 0.23642969, 0.7056997 , 0.97163859],
       [0.56187442, 0.89408208, 0.94536562, 0.71965322, 0.43279208],
       [0.48124397, 0.80269911, 0.94173871, 0.20069594, 0.69333081]])

In [33]:
np.random.randn(1) # Create a random number from standard normal distribution

array([-1.80366417])

In [34]:
np.random.randn(5) # Create 5 random numbers from standard normal distribution

array([-0.30313342, -0.15916344,  1.07836222,  0.40704724,  0.00991524])

In [35]:
np.random.normal(1,2,3) # Create 3 random numbers from normal with mean 1 and SD 2

array([-0.77638187, -0.76506298, -1.80922232])

In [36]:
np.random.randint(1,100,10) # Return 10 random integers between 1 (inclusive) and 100 (exclusive)

array([84, 11, 73, 50,  8, 35, 74, 84, 91, 54])

In [37]:
np.random.seed(42) # Set seed to generate same random numbers (Should be in the same cell)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [38]:
arr = np.arange(25)

In [39]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [40]:
ranarr = np.random.randint(0,50,10)

In [41]:
ranarr

array([38, 18, 22, 10, 10, 23, 35, 39, 23,  2])

In [42]:
arr.shape

(25,)

In [43]:
arr.reshape(5,5) # Repshape my array to a matrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [44]:
ranarr.max() # Finding the maximum value of "ranarr" array

39

In [45]:
ranarr.min() # Finding the minimum value of "ranarr" array

2

In [46]:
ranarr

array([38, 18, 22, 10, 10, 23, 35, 39, 23,  2])

In [47]:
ranarr.argmax() # what is the index of larget value. Note: In Python index start with zero

7

In [48]:
ranarr.argmin() # what is the index of smallest value. Note: In Python index start with zero

9

In [49]:
ranarr.dtype # Identify type of the data in an array

dtype('int32')

### NumPy Indexing and Selection

In [51]:
arr = np.arange(0,11)

In [52]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [53]:
arr[8] ## Slect the value at 8th position

8

In [54]:
arr[1:5] ## Select values in index 1 to 5, excluding 5

array([1, 2, 3, 4])

In [55]:
arr[0:5] ## Select values in index 0 to 5, excluding 5 

array([0, 1, 2, 3, 4])

In [56]:
arr[:5] ## Values starting from begining upto index 5

array([0, 1, 2, 3, 4])

In [57]:
arr[5:] ## Values starting from index 5 to all the way to end

array([ 5,  6,  7,  8,  9, 10])

In [58]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [59]:
new_arr = arr / 2 ## Make chnages to the array and save it use later

In [60]:
new_arr

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [61]:
arr ** 2 ## Square each value of the array

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [62]:
slice_of_arr = arr[0:6]

In [63]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [64]:
slice_of_arr[:] ## Grab all the elements in the array

array([0, 1, 2, 3, 4, 5])

In [65]:
slice_of_arr[:] = 99

In [66]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [67]:
arr ## NOTE: We have slice the arrange and change the values in the new arra. But still values of the original array has been chnaged. 
## If we do not want this to happens we have to explicitly say we want to create a copy of the original array

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [68]:
arr_copy = arr.copy() ## Make a copy of an array and make sure when make changes original array is not affected by it

In [69]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [70]:
arr_copy[:] = 1000

In [71]:
arr_copy

array([1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000])

In [72]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [73]:
#### Indexing on 2-dimentional array (matrix)

In [74]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [75]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [76]:
arr_2d.shape ## Cheecked the shape of the matrix we just created

(3, 3)

In [77]:
arr_2d[1] ## Row index is 1 (as similar to array indexing, indexing start with zero)

array([20, 25, 30])

In [78]:
arr_2d[1][1] ## Row index is 1 and column index is 1

25

In [79]:
arr_2d[1,1] ## Alteratively to two square brackets indexing

25

In [80]:
arr_2d[2][2]

45

In [81]:
arr_2d[2,2]

45

In [82]:
## Let we want to select a small subset (matrix) from the arr_2d 

In [83]:
arr_2d[:2,]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [84]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [85]:
## Conditional selections

In [86]:
arr = np.arange(1,11)

In [87]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [88]:
arr > 4 ## Return numpy array for boolian (whether each value is grbeater than 4)

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [89]:
bool_arr = arr>4

In [90]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [91]:
arr[bool_arr] ## From the original array. only true index are returned
## BUT, usually we do not do this in multiple steps. We implement in one step

array([ 5,  6,  7,  8,  9, 10])

In [92]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

In [93]:
arr[arr==2]

array([2])

In [94]:
arr[arr <= 6]

array([1, 2, 3, 4, 5, 6])

### NumPy Operations

In [96]:
arr = np.arange(0,10)

In [97]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [98]:
### Simple Operation

In [99]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109])

In [100]:
arr / 100

array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09])

In [101]:
arr ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [102]:
(arr + 2)/100

array([0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 , 0.11])

In [103]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [104]:
1/arr ## devide by zero. Still NumPy gives warning and remaining valid values

C:\Users\sulal\AppData\Local\Temp\ipykernel_25096\1111233972.py:1: RuntimeWarning: divide by zero encountered in divide
  1/arr ## devide by zero. Still NumPy gives warning and remaining valid values


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [105]:
arr/arr

C:\Users\sulal\AppData\Local\Temp\ipykernel_25096\1862401812.py:1: RuntimeWarning: invalid value encountered in divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [106]:
## np have variety of functions we can apply for our array

In [107]:
np.sqrt(arr) 

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [108]:
np.log(arr) ## log(0) is -inf

C:\Users\sulal\AppData\Local\Temp\ipykernel_25096\2273272014.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr) ## log(0) is -inf


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [109]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [110]:
## Summary statistics

In [111]:
np.sum(arr)

45

In [112]:
np.mean(arr)

4.5

In [113]:
np.max(arr)

9

In [114]:
## Operations on two dimentional arrays (matrices)

In [115]:
arr_2d = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [116]:
arr_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [117]:
arr_2d.shape

(3, 4)

In [118]:
arr_2d.sum() ## Sum of all the elements in the array

78

In [119]:
## Sum all the elements on the rows/columns

In [120]:
## To check options under sum(), press shift+tab after sum()
## Give me the sum, across the row
arr_2d.sum(axis = 0) ## Returns the sum of the values in the columns

array([15, 18, 21, 24])

In [121]:
arr_2d.sum(axis=1) ## Returns the sum of the vlaues in the rows

array([10, 26, 42])